{{ if .Values.rbac.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-job-operator
  labels:
    app: tf-job-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-job-dashboard
  labels:
    app: tf-job-dashboard
{{ end }}
