apiVersion: "kubeflow.org/v1alpha1"
kind: "TFJob"
metadata:
  name: {{ .Release.Name }}
spec:
  replica_specs:
    - replicas: 1
      tfPort: 2222
      tfReplicaType: MASTER
      template:
        spec:
          containers:
            - image: {{ .Values.image }}
              name: tensorflow
          restartPolicy: OnFailure
    - replicas: 1
      tfPort: 2222
      tfReplicaType: WORKER
      template:
        spec:
          containers:
            - image: {{ .Values.image }}
              name: tensorflow
          restartPolicy: OnFailure
